export interface ThemeConfig {
  name: string;
  colors: {
    primary: string;
    secondary: string;
    background: string;
    surface: string;
    surfaceSecondary: string;
    border: string;
    text: string;
    textSecondary: string;
    textMuted: string;
    accent: string;
    accentHover: string;
    success: string;
    successHover: string;
    warning: string;
    warningHover: string;
    error: string;
    errorHover: string;
    lineNumber: string;
    lineNumberBg: string;
  };
}

export const themes: Record<string, ThemeConfig> = {
  dark: {
    name: "Dark",
    colors: {
      primary: "#1f2937",
      secondary: "#ffffff",
      background: "#0D0D0D",
      surface: "#111111",
      surfaceSecondary: "#ffffff",
      border: "#ffffff",
      text: "#f9fafb",
      textSecondary: "#d1d5db",
      textMuted: "#9ca3af",
      accent: "#3b82f6",
      accentHover: "#2563eb",
      success: "#10b981",
      successHover: "#059669",
      warning: "#f59e0b",
      warningHover: "#d97706",
      error: "#ef4444",
      errorHover: "#dc2626",
      lineNumber: "#6b7280",
      lineNumberBg: "#0f172a",
    },
  },
  light: {
    name: "Light",
    colors: {
      primary: "#ffffff",
      secondary: "#f8fafc",
      background: "#f1f5f9",
      surface: "#ffffff",
      surfaceSecondary: "#f8fafc",
      border: "#e2e8f0",
      text: "#2D4E74",
      textSecondary: "#334155",
      textMuted: "#64748b",
      accent: "#3b82f6",
      accentHover: "#2563eb",
      success: "#10b981",
      successHover: "#059669",
      warning: "#f59e0b",
      warningHover: "#d97706",
      error: "#ef4444",
      errorHover: "#dc2626",
      lineNumber: "#64748b",
      lineNumberBg: "#f8fafc",
    },
  },
  coffee: {
    name: "Coffee",
    colors: {
      primary: "#3c2415",
      secondary: "#5d4037",
      background: "#2e1a0d",
      surface: "#3c2415",
      surfaceSecondary: "#5d4037",
      border: "#8d6e63",
      text: "#f5f5dc",
      textSecondary: "#d7ccc8",
      textMuted: "#a1887f",
      accent: "#ff8a50",
      accentHover: "#ff7043",
      success: "#8bc34a",
      successHover: "#689f38",
      warning: "#ffc107",
      warningHover: "#ff8f00",
      error: "#f44336",
      errorHover: "#d32f2f",
      lineNumber: "#8d6e63",
      lineNumberBg: "#2e1a0d",
    },
  },
  greenish: {
    name: "Light Greenish",
    colors: {
      primary: "#f0f9f0",
      secondary: "#e8f5e8",
      background: "#f8fdf8",
      surface: "#ffffff",
      surfaceSecondary: "#f0f9f0",
      border: "#c8e6c9",
      text: "#2D7A66",
      textSecondary: "#2e7d32",
      textMuted: "#4caf50",
      accent: "#4caf50",
      accentHover: "#43a047",
      success: "#66bb6a",
      successHover: "#4caf50",
      warning: "#ff9800",
      warningHover: "#f57c00",
      error: "#f44336",
      errorHover: "#d32f2f",
      lineNumber: "#81c784",
      lineNumberBg: "#e8f5e8",
    },
  },
  pinky: {
    name: "Pinky",
    colors: {
      primary: "#fce4ec",
      secondary: "#f8bbd9",
      background: "#fdf2f8",
      surface: "#ffffff",
      surfaceSecondary: "#fce4ec",
      border: "#f48fb1",
      text: "#E73CA4",
      textSecondary: "#ad1457",
      textMuted: "#c2185b",
      accent: "#e91e63",
      accentHover: "#d81b60",
      success: "#4caf50",
      successHover: "#43a047",
      warning: "#ff9800",
      warningHover: "#f57c00",
      error: "#f44336",
      errorHover: "#d32f2f",
      lineNumber: "#f48fb1",
      lineNumberBg: "#fce4ec",
    },
  },
  midnight: {
    name: "Midnight Blue",
    colors: {
      primary: "#1a237e",
      secondary: "#283593",
      background: "#020930",
      surface: "#01093d",
      surfaceSecondary: "#283593",
      border: "#3f51b5",
      text: "#e8eaf6",
      textSecondary: "#c5cae9",
      textMuted: "#9fa8da",
      accent: "#5c6bc0",
      accentHover: "#3f51b5",
      success: "#4caf50",
      successHover: "#43a047",
      warning: "#ff9800",
      warningHover: "#f57c00",
      error: "#f44336",
      errorHover: "#d32f2f",
      lineNumber: "#7986cb",
      lineNumberBg: "#0d1757",
    },
  },
  wine: {
    name: "Wine Red",
    colors: {
      primary: "#4a0e0e",
      secondary: "#6d1a1a",
      background: "#1f0101",
      surface: "#360101",
      surfaceSecondary: "#6d1a1a",
      border: "#8b2635",
      text: "#ffebee",
      textSecondary: "#ffcdd2",
      textMuted: "#ef9a9a",
      accent: "#e57373",
      accentHover: "#ef5350",
      success: "#4caf50",
      successHover: "#43a047",
      warning: "#ff9800",
      warningHover: "#f57c00",
      error: "#f44336",
      errorHover: "#d32f2f",
      lineNumber: "#ef5350",
      lineNumberBg: "#2d0a0a",
    },
  },
  cabernet: {
    name: "Cabernet Red",
    colors: {
      primary: "#3c0a0a",
      secondary: "#5d1a1a",
      background: "#2a0606",
      surface: "#3c0a0a",
      surfaceSecondary: "#5d1a1a",
      border: "#8b2635",
      text: "#ffeaea",
      textSecondary: "#ffcccb",
      textMuted: "#ff9999",
      accent: "#cd5c5c",
      accentHover: "#b22222",
      success: "#4caf50",
      successHover: "#43a047",
      warning: "#ff9800",
      warningHover: "#f57c00",
      error: "#f44336",
      errorHover: "#d32f2f",
      lineNumber: "#cd5c5c",
      lineNumberBg: "#2a0606",
    },
  },
  lightShades: {
    name: "Light Shades",
    colors: {
      primary: "#ffffff",
      secondary: "#f7fafc",
      background: "#edf2f7",
      surface: "#ffffff",
      surfaceSecondary: "#f7fafc",
      border: "#e2e8f0",
      text: "#65788A",
      textSecondary: "#4a5568",
      textMuted: "#718096",
      accent: "#667eea",
      accentHover: "#5a6fd8",
      success: "#48bb78",
      successHover: "#38a169",
      warning: "#ed8936",
      warningHover: "#dd6b20",
      error: "#f56565",
      errorHover: "#e53e3e",
      lineNumber: "#a0aec0",
      lineNumberBg: "#f7fafc",
    },
  },
  darkShades: {
    name: "Dark Shades",
    colors: {
      primary: "#2d3748",
      secondary: "#4a5568",
      background: "#11151c",
      surface: "#19202b",
      surfaceSecondary: "#4a5568",
      border: "#a35b02",
      text: "#fc9e2b",
      textSecondary: "#e2e8f0",
      textMuted: "#cbd5e0",
      accent: "#667eea",
      accentHover: "#5a6fd8",
      success: "#48bb78",
      successHover: "#38a169",
      warning: "#ed8936",
      warningHover: "#dd6b20",
      error: "#f56565",
      errorHover: "#e53e3e",
      lineNumber: "#a0aec0",
      lineNumberBg: "#1a202c",
    },
  },
};

export const defaultTheme = "dark";